CreateSubscription:
    pattern: /create-subscription/{pleskhost}/{pleskuser}/{pleskpass}/{hostname}/{ip}/{ftplogin}/{ftppass}
    defaults: { _controller: DellaertPleskRemoteControlBundle:Test:createSubscription}

CreateUser:
    pattern: /create-user/{pleskhost}/{pleskuser}/{pleskpass}/{subscription}/{userlogin}/{userpass}/{username}
    defaults: { _controller: DellaertPleskRemoteControlBundle:Test:createUser}
    $dbname,$dbtype,$dbserver

CreateDatabase:
    pattern: /create-database/{pleskhost}/{pleskuser}/{pleskpass}/{subscription}/{dbname}/{dbtype}/{dbserver}
    defaults: { _controller: DellaertPleskRemoteControlBundle:Test:createDatabase}