SubscriptionCreate:
    pattern: /create-subscription/{pleskhost}/{pleskuser}/{pleskpass}/{hostname}/{ip}/{ftplogin}/{ftppass}
    defaults: { _controller: DellaertPleskRemoteControlBundle:Test:createSubscription}
