CreateSubscription:
    pattern: /create-subscription/{pleskhost}/{pleskuser}/{pleskpass}/{hostname}/{ip}/{ftplogin}/{ftppass}
    defaults: { _controller: DellaertPleskRemoteControlBundle:Test:createSubscription}

CreateUser:
    pattern: /create-user/{pleskhost}/{pleskuser}/{pleskpass}/{subscription}/{userlogin}/{userpass}/{username}
    defaults: { _controller: DellaertPleskRemoteControlBundle:Test:createUser}

CreateDatabase:
    pattern: /create-database/{pleskhost}/{pleskuser}/{pleskpass}/{subscription}/{dbname}/{dbtype}/{dbserver}
    defaults: { _controller: DellaertPleskRemoteControlBundle:Test:createDatabase}

CreateDatabaseUser:
    pattern: /create-databaseuser/{pleskhost}/{pleskuser}/{pleskpass}/{dbid}/{username}/{userpass}
    defaults: { _controller: DellaertPleskRemoteControlBundle:Test:createDatabaseUser}